EPOCHS = 10
BATCH_SIZE = 16
BATCH_ELEMENT = 4 
N_EVAL = 100
CSV_PATH="./datasets/train.csv"
IMAGE_DIR="./datasets/train/"
IMAGE_SIZE = (224,224)
NUM_CLASSES = 5005 # Checked how many distinct labels
PERCENT_TRAIN=.8
MARGIN = 1